#pragma once
	
#ifdef __clang__
#define GLM_SWIZZLE_GEN_VEC2_ENTRY(L, T, Q, CONST, A, B)	\
	GLM_FUNC_QUALIFIER vec<2, T, Q> __attribute__((always_inline)) A ## B() const							\
	{													\
		using E = ElementCollection<L, T, Q>; \
		using G = typename vec<L, T, Q>::GccVec_t; \
		G vin; std::memcpy(&vin, &data, std::min(sizeof(data), sizeof(vin))); \
		GccVec<2, T, Q> vout; \
		static constexpr E testObj{};\
		static constexpr auto pA = &testObj.A;\
		static constexpr auto pB = &testObj.B;\
		vout=__builtin_shufflevector(vin, vin, getOffset<pA, &testObj>(), getOffset<pB, &testObj>()); \
		return vec<2, T, Q>(vout);			\
	}

#define GLM_SWIZZLE_GEN_VEC3_ENTRY(L, T, Q, CONST, A, B, C)		\
	GLM_FUNC_QUALIFIER vec<3, T, Q> __attribute__((always_inline)) A ## B ## C() const							\
	{															\
		using E = ElementCollection<L, T, Q>; \
		using G = typename vec<L, T, Q>::GccVec_t; \
		G vin; std::memcpy(&vin, &data, std::min(sizeof(data), sizeof(vin))); \
		GccVec<4, T, Q> vout; \
		static constexpr E testObj{};\
		static constexpr auto pA = &testObj.A;\
		static constexpr auto pB = &testObj.B;\
		static constexpr auto pC = &testObj.C;\
		vout=__builtin_shufflevector(vin, vin, getOffset<pA, &testObj>(), getOffset<pB, &testObj>(), getOffset<pC, &testObj>(), -1); \
		vec<3, T, Q> voutfin; std::memcpy(&voutfin, &vout, sizeof(voutfin)); \
		return voutfin;			\
	}

#define GLM_SWIZZLE_GEN_VEC4_ENTRY(L, T, Q, CONST, A, B, C, D)					\
	GLM_FUNC_QUALIFIER vec<4, T, Q> __attribute__((always_inline)) A ## B ## C ## D() const									\
	{																		\
		using E = ElementCollection<L, T, Q>; \
		using G = typename vec<L, T, Q>::GccVec_t; \
		G vin; std::memcpy(&vin, &data, std::min(sizeof(data), sizeof(vin))); \
		GccVec<4, T, Q> vout; \
		static constexpr E testObj{};\
		static constexpr auto pA = &testObj.A;\
		static constexpr auto pB = &testObj.B;\
		static constexpr auto pC = &testObj.C;\
		static constexpr auto pD = &testObj.D;\
		vout=__builtin_shufflevector(vin, vin, getOffset<pA, &testObj>(), getOffset<pB, &testObj>(), getOffset<pC, &testObj>(), getOffset<pD, &testObj>()); \
		return vec<4, T, Q>(vout);			\
	}

#define GLM_SWIZZLE_GEN_VEC2_ENTRY_DEF(T, Q, L, CONST, A, B)	\
	template<typename T>										\
	GLM_FUNC_QUALIFIER vec<L, T, Q> vec<L, T, Q>::A ## B() const					\
	{															\
		return vec<2, T, Q>(this->A, this->B);					\
	}

#define GLM_SWIZZLE_GEN_VEC3_ENTRY_DEF(T, Q, L, CONST, A, B, C)		\
	template<typename T>											\
	GLM_FUNC_QUALIFIER vec<3, T, Q> vec<L, T, Q>::A ## B ## C() const					\
	{																\
		return vec<3, T, Q>(this->A, this->B, this->C);				\
	}

#define GLM_SWIZZLE_GEN_VEC4_ENTRY_DEF(T, Q, L, CONST, A, B, C, D)		\
	template<typename T>												\
	GLM_FUNC_QUALIFIER vec<4, T, Q> vec<L, T, Q>::A ## B ## C ## D() const					\
	{																	\
		return vec<4, T, Q>(this->A, this->B, this->C, this->D);		\
	}

#define GLM_MUTABLE

#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, B, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, A, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, B, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, X, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, X, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, A, X) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, B, X)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC2(T, Q) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, x, y) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, r, g) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, s, t)

#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, Q, A, B, C) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, A, A) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, B, B) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, C, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, A, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, B, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, B, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, C, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, C, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, X, A) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, X, B) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, X, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, A, X) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, B, X) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, C, X)


#define GLM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, Q, A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, B, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, C, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, A, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, C, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, A, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, B, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, A, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, B, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, C, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, A, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, B, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, C, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, X, X, C)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, A, B, C) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, Q, A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, Q, A, B, C)
	
#define GLM_SWIZZLE_GEN_VEC_FROM_VEC3(T, Q) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, x, y, z) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, r, g, b) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, s, t, p)

#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, X) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, X) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, X) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, X) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, X, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, X, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, X, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, X, D)
#define GLM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, X, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, X, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, X, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, X, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, X, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, X, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, X, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, X, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, A, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, B, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, C, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , X, D, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, X, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, X, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, X, X) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, X, X)
	


#define GLM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, A) \
	\
	\
	/*one-lane undefined, all unique components:*/\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, C, A) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, X, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, X, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, X, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, X, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, X, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, X, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, X, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, X, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, X, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, X, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, X, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, X, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, X, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, X, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, X, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, X, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, X, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, X, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, X, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, X, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, X, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, X, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, X, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, X, C, A) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, X, A) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, X) \
	\
	/*swizzles w/ duplicate components:*/\
	\
	/*two lanes undefined: both unique components and duplicate components*/\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, D, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, D, C) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, X, C) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, C, X) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, X, X ) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, X, X) \
	/* end of two lanes undefined */\
	/* three lanes undefined: */\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, X, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, X, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, X, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, X, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, A, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, B, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, C, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, X, D, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, A, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, B, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, C, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , X, D, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, X, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, X, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, X, X, X) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, X, X, X) \
	/* end of three lanes undefined */\
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, D, C) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, D)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	\
	GLM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC4(T, Q) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, x, y, z, w) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, r, g, b, a) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, s, t, p, q)
#else
#define GLM_SWIZZLE_GEN_VEC2_ENTRY(L, T, Q, CONST, A, B)	\
	GLM_FUNC_QUALIFIER vec<2, T, Q> __attribute__((always_inline)) A ## B() const							\
	{													\
		using E = ElementCollection<L, T, Q>; \
		using G = typename vec<L, T, Q>::GccVec_t; \
		G vin; std::memcpy(&vin, &data, std::min(sizeof(data), sizeof(vin))); \
		GccVec<2, T, Q> vout; \
		vout = __builtin_shufflevector(vin, vin, offsetof(E, A)/sizeof(A), offsetof(E, B)/sizeof(B)); \
		return vec<2, T, Q>(vout);			\
	}

#define GLM_SWIZZLE_GEN_VEC3_ENTRY(L, T, Q, CONST, A, B, C)		\
	GLM_FUNC_QUALIFIER vec<3, T, Q> __attribute__((always_inline)) A ## B ## C() const							\
	{															\
		using E = ElementCollection<L, T, Q>; \
		using G = typename vec<L, T, Q>::GccVec_t; \
		G vin; std::memcpy(&vin, &data, std::min(sizeof(data), sizeof(vin))); \
		GccVec<4, T, Q> vout; \
		vout = __builtin_shufflevector(vin, vin, offsetof(E, A)/sizeof(A), offsetof(E, B)/sizeof(B), offsetof(E, C)/sizeof(C), -1); \
		vec<3, T, Q> voutfin; std::memcpy(&voutfin, &vout, sizeof(voutfin)); \
		return voutfin;			\
	}

#define GLM_SWIZZLE_GEN_VEC4_ENTRY(L, T, Q, CONST, A, B, C, D)					\
	GLM_FUNC_QUALIFIER vec<4, T, Q> __attribute__((always_inline)) A ## B ## C ## D() const									\
	{																		\
		using E = ElementCollection<L, T, Q>; \
		using G = typename vec<L, T, Q>::GccVec_t; \
		G vin; std::memcpy(&vin, &data, std::min(sizeof(data), sizeof(vin))); \
		GccVec<4, T, Q> vout; \
		vout=__builtin_shufflevector(vin, vin, offsetof(E, A)/sizeof(A), offsetof(E, B)/sizeof(B), offsetof(E, C)/sizeof(C), offsetof(E, D)/sizeof(D)); \
		return vec<4, T, Q>(vout);			\
	}

#define GLM_SWIZZLE_GEN_VEC2_ENTRY_DEF(T, Q, L, CONST, A, B)	\
	template<typename T>										\
	GLM_FUNC_QUALIFIER vec<L, T, Q> vec<L, T, Q>::A ## B() const					\
	{															\
		return vec<2, T, Q>(this->A, this->B);					\
	}

#define GLM_SWIZZLE_GEN_VEC3_ENTRY_DEF(T, Q, L, CONST, A, B, C)		\
	template<typename T>											\
	GLM_FUNC_QUALIFIER vec<3, T, Q> vec<L, T, Q>::A ## B ## C() const					\
	{																\
		return vec<3, T, Q>(this->A, this->B, this->C);				\
	}

#define GLM_SWIZZLE_GEN_VEC4_ENTRY_DEF(T, Q, L, CONST, A, B, C, D)		\
	template<typename T>												\
	GLM_FUNC_QUALIFIER vec<4, T, Q> vec<L, T, Q>::A ## B ## C ## D() const					\
	{																	\
		return vec<4, T, Q>(this->A, this->B, this->C, this->D);		\
	}

#define GLM_MUTABLE

#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, B, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, A, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(2, T, Q, GLM_MUTABLE, B, B)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC2(T, Q) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, x, y) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, r, g) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, Q, s, t)

#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, Q, A, B, C) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, A, A) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, B, B) \
  GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, C, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, A, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, B, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, B, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, C, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(3, T, Q, GLM_MUTABLE, C, B)

#define GLM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, Q, A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, A, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, B, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(3, T, Q, GLM_MUTABLE, C, B, B)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, Q, A, B, C) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, Q, A, B, C)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC3(T, Q) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, x, y, z) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, r, g, b) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMQ(T, Q, s, t, p)

#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, D) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, A, A) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, B, B) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, C, C) \
	GLM_SWIZZLE_GEN_VEC2_ENTRY(4, T, Q, GLM_MUTABLE, D, D)

#define GLM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , A, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , B, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , C, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, D, C) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, D) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, A, A) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, B, B) \
	GLM_SWIZZLE_GEN_VEC3_ENTRY(4, T, Q, , D, C, C)

#define GLM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, A) \
	/*swizzles w/ duplicate components:*/\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, B, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , A, D, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, B, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , B, D, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, B, D, C) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , C, D, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, A, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, B, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, C, D, D) \
	\
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, A, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, B, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, C, D) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, A) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, B) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, C) \
	GLM_SWIZZLE_GEN_VEC4_ENTRY(4, T, Q, , D, D, D, D)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D) \
	GLM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, Q, A, B, C, D)

#define GLM_SWIZZLE_GEN_VEC_FROM_VEC4(T, Q) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, x, y, z, w) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, r, g, b, a) \
	GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMQ(T, Q, s, t, p, q)
#endif